version: 1.1

trak:
  local: https://localhost:5666
  remote: https://mcaq.me:5666

tasks:
  basic_task:
    name: Basic
    type: docker
    giturl: https://raw.githubusercontent.com/SharpSet/
    compose: /sharpcd/dev/testing/basic.yml
