version: 0.1

tasks:

  testing:
    name: Testing Task v0.1
    type: docker
    sharpurl: https://localhost:5666
    envfile: .env
    giturl: https://github.com/Sharpz7/test
    command: |
      cat 32
      ghiagaown

  testing2:
    name: Testing Task v0.2
    type: git
    sharpurl: https://localhost:5666
    envfile: .envfile
    giturl: https://github.com/Sharpz7/test2
    command: |
      tv 56
      tnnfuie4nfu