version: 2

variables:
  DOCKER_DRIVER: overlay2

jobs:
  testing:
    docker:
      - image: sharp6292/gopack:0.1.2

    steps:
      - checkout

      - run:
          name: compile
          command: |
            gopack --file --dev install

            go build -o "sharpcd" ./src

          environment:
            GOOS: "linux"

      - run:
          name: Get Keys
          command: |
            mkdir ./private
            openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout ./private/server.key -out ./private/server.crt -config ./.circleci/openssl.conf -extensions 'v3_req'

      - run:
          name: Create Password
          command: |
            ./sharpcd --pass Pass123 setpass

      - run:
          name: run_server
          background: true
          command: |
            ./sharpcd server

      - run:
          name: testing
          command: |
            sleep 2
            ./sharpcd --pass Pass123

workflows:
  version: 2
  workflow:
    jobs:
      - testing
