version: 2

variables:
  DOCKER_DRIVER: overlay2

jobs:
  testing:
    docker:
      - image: sharp6292/gopack:0.1.2

    steps:
      - checkout

      - run:
          name: compile
          command: |
            gopack --file --dev install

            go build -o "./internal/sharpcd" ./src

          environment:
            GOOS: "linux"

      - run:
          name: Get Keys
          command: |
            openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout ./internal/private/server.key -out ./internal/private/server.crt -config ./internal/private/openssl.conf -extensions 'v3_req'

      - run:
          name: Create Secret
          command: |
            ./internal/sharpcd --secret Secret123 setsecret

      - run:
          name: run_server
          background: true
          command: |
            ./internal/sharpcd addfilter https://raw.githubusercontent.com/Sharpz7/sharpcd/testing
            ./internal/sharpcd server

      - run:
          name: testing
          command: |
            sleep 2
            ./internal/sharpcd --secret Secret123
            curl -k -X POST -d {"secret":"Secret123"} https://localhost:5666/api/jobs/

workflows:
  version: 2
  workflow:
    jobs:
      - testing
