version: 2

variables:
  DOCKER_DRIVER: overlay2

jobs:
  testing:
    docker:
      - image: sharp6292/ci-gopack:0.0.1a

    steps:
      - checkout

      - run:
          name: compile
          command: |
            go get /go/src/gopkg.in/yaml.v2
            go build -o "sharpcd" ./src

          environment:
            GOOS: "linux"

      - run:
          name: run_server
          background: true
          command: |
            ./sharpcd server

      - run:
          name: Get Keys
          command: |
            mkdir ./private
            openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout ./private/server.key -out ./private/server.crt -config ./.circleci/openssl.conf -extensions 'v3_req'

      - run:
          name: testing
          command: |
            apk add lsof

            sleep 2
            ./sharpcd

workflows:
  version: 2
  workflow:
    jobs:
      - testing
