version: 2

variables:
  DOCKER_DRIVER: overlay2

jobs:
  testing:
    docker:
      - image: sharp6292/ci-gopack:0.0.1a

    steps:
      - checkout

      - run:
          name: compile
          command: |
            go build -o "sharpcd" ./src

          environment:
            GOOS: "linux"

      - run:
          name: run_server
          command: |
            ./sharpcd server </dev/null &>/dev/null &

            wget -qO- --post-data "" localhost:5666

      - run:
          name: run_server
          command: |
            wget -qO- --post-data "" localhost:5666

workflows:
  version: 2
  workflow:
    jobs:
      - testing
