version: '3'
services:
  hello_world:
    image: ubuntu
    command: tail -f /dev/null

    volumes:
      - "externalv:/test"

networks:
  default:
      external:
          name: external1

volumes:
  externalv:
    external: True
