version: 1.1

trak:
  local: https://localhost:5666
  remote: https://mcaq.me:5666

tasks:
  basic_task:
    name: Basic
    type: docker
    sharpurl: https://localhost:5666
    giturl: https://raw.githubusercontent.com/Sharpz7/
    compose: /sharpcd/dev/testing/basic.yml

  env_task:
    name: Enviroment Test Pass
    type: docker
    envfile: ./testing/.env
    sharpurl: https://localhost:5666
    giturl: https://raw.githubusercontent.com/Sharpz7/
    compose: /sharpcd/dev/testing/env.yml
